serveraddr: 127.0.0.1
serverport: "8060"
rpchost: 0.0.0.0
rpcport: "9060"
sync: true
isproduct: false
userkeydir: ./conf/user.key
userpubdir: ./conf/user.pub
adminkeydir: ./conf/admin.key
adminpubdir: ./conf/admin.pub
db:
  host: 0.0.0.0
  port: "5432"
  driver: postgres
  databasename: business
  username: business
  password: business
  maxidleconn: 200
  maxopenconn: 2000
rdb:
  host: 0.0.0.0
  port: "6379"
  db: 0
  password: "123456"
istls: false
tls: null
iscaptcha: false
logdir: ./log
