serverAddr: 0.0.0.0
serverPort: "8060"
rpcHost: 0.0.0.0
rpcPort: "9060"
sync: true
isProduct: false
userKeyDir: ./conf/user.key
userPubDir: ./conf/user.pub
adminKeyDir: ./conf/admin.key
adminPubDir: ./conf/admin.pub
db:
  host: 192.168.31.181
  port: "30432"
  driver: postgres
  databasename: business
  username: business
  password: business
  maxidleconn: 200
  maxopenconn: 2000
rdb:
  host: 192.168.31.183
  port: "30379"
  db: 0
  password: business
isTLS: false
tls: null
