definitions:
  app.Meta:
    properties:
      error:
        type: object
      msg:
        type: string
      status:
        type: integer
    type: object
  app.Response:
    properties:
      data:
        type: object
      meta:
        $ref: '#/definitions/app.Meta'
        type: object
    type: object
  utils.FormIDCard:
    properties:
      birthday:
        description: 出生日期
        type: string
      idCard:
        description: 身份证号
        type: string
      idCardAddr:
        description: 身份证地址
        type: string
      issueOrg:
        description: 身份证发证机关
        type: string
      name:
        type: string
      nation:
        type: string
      sex:
        type: integer
      validPeriod:
        description: 有效时期
        type: string
    required:
    - birthday
    - idCard
    - idCardAddr
    - issueOrg
    - name
    - nation
    - sex
    - validPeriod
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/changeLoginPasswd:
    post:
      consumes:
      - application/json
      parameters:
      - description: 旧密码
        in: query
        name: oldPwd
        required: true
        type: string
      - description: 新密码
        in: query
        name: newPwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 修改用户密码
      tags:
      - 用户
  /api/v1/editHeadIcon:
    post:
      consumes:
      - application/json
      parameters:
      - description: 头像
        in: query
        name: headIcon
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 修改用户头像
      tags:
      - 用户
  /api/v1/getHeadIcon:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取用户头像
      tags:
      - 用户
  /api/v1/getUserProfile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取个人信息
      tags:
      - 用户
  /api/v1/login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户登出
      tags:
      - 用户
  /api/v1/register:
    post:
      parameters:
      - description: Phone
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Code
        in: body
        name: code
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 用户注册
      tags:
      - 用户
  /api/v1/userUpdate:
    post:
      parameters:
      - description: 昵称
        in: body
        name: nickname
        schema:
          type: string
      - description: 用户名,之可以修改一次
        in: body
        name: username
        schema:
          type: string
      - description: 手机号码
        in: body
        name: Phone
        schema:
          type: string
      - description: 签名
        in: body
        name: sign
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新用户信息
      tags:
      - 用户
swagger: "2.0"
